### ISSUE TITLE
Servo code missing original copyright

### ISSUE THREAD

**Issue by michaelmargolis** [CommunityGD32Cores/ArduinoCore-GD32#30]
The code for the servo class and header are copied from the Arduino AVR source code but the copyright statements have been removed.  Please ensure that all copyright material used in this repository include existing copyright statements

**Comment by maxgerhardt** [comment]
The servo class can impossibly be from the AVR core because it uses HardwareTimer, that doesn't exist in the AVR core.

https://github.com/CommunityGD32Cores/ArduinoCore-GD32/blob/2f1adfb0d687db72b0598ea3c3bbf217a0446ce5/libraries/Servo/src/Servo.cpp#L1-L4

I'll review the header more closely.

**Comment by maxgerhardt** [comment]
The header seems to be mostly from 

https://github.com/arduino-libraries/Servo/blob/f3617664917ff1a46c2c3db5300d27054ba147cc/src/Servo.h#L80-L122

that is correct. Will add.

**Comment by maxgerhardt** [comment]
Resolved in a68917a6c70a91eae9ae04624eb27f02fc11f475, 2b34964f3c066bf9da0c849cd96a3f86a3ae121e, ca0173f5dd71cadbf2ee01f5d76bcb417eeaddf9 and 50134d93cd1689015ce1a5e00ef7d8b07da1bd5d

**Comment by michaelmargolis** [comment]
Thank you for your prompt reply.

Although the interrupt code is different, the Servo class appears identical.
In this case you can add the copyright of the author of interrupt code to the original copyright.

Michael Margolis (author of the servo code)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by maxgerhardt** [comment]
All done already, see above commit references.

**Comment by michaelmargolis** [comment]
thanks and have fun with the project

Michael
________________________________
