### ISSUE TITLE
GD32F130C6 Tone and PWM doesn't work

### ISSUE THREAD

**Issue by maxgerhardt** [CommunityGD32Cores/ArduinoCore-GD32#66]
Per https://github.com/CommunityGD32Cores/platform-gd32/discussions/28.

No output when using provided standard code.

**Comment by maxgerhardt** [comment]
Fixed a criticial issue in https://github.com/CommunityGD32Cores/ArduinoCore-GD32/commit/6ba49c865388ff9dfc78f07e4e4d7f513631cb38 and it's workig on my GD32F190C6, but per discussion still no output on a real GD32F130, need to wait until realHW arrives.

**Comment by djix123** [comment]
I have a GD32F130F8 to hand. Is there anything I can test?

**Comment by maxgerhardt** [comment]
If you can test the sketch
```cpp
#include <Arduino.h>
PWM servo(PWM0);    // PA0

void captureCompareCallback(void);

void setup()
{
    pinMode(PB9, OUTPUT);

    // 1000Hz, 50% on-time.
    servo.setPeriodCycle(1000, 50, FORMAT_HZ);
    servo.attachInterrupt(captureCompareCallback);
    servo.start();
}

// the loop function runs over and over again forever
void loop() { }

// capture compare interrupt callback function
void captureCompareCallback(void)
{
    digitalToggle(PB9);
}
```
with `platformio.ini`
```ini
[env:genericGD32F130F8]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
board = genericGD32F130F8
framework = arduino
```
and see whether there is output on PA0 and/or PB0, that would be great.
Make sure to use [the CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) to `pio platform update https://github.com/CommunityGD32Cores/platform-gd32.git` before though.

**Comment by djix123** [comment]
Yes, that works on a GD32F130F8. Changed PB9 to PB1 since PB9 isn't available of the GD32F130F8. See attached screenshot
<img width="1201" alt="Screen Shot 2022-06-05 at 8 39 22 AM" src="https://user-images.githubusercontent.com/5787330/172050966-c533c9c6-054a-476a-a519-febb40a2fa02.png">
.

**Comment by maxgerhardt** [comment]
Confirmed fixed in discussion.
