### ISSUE TITLE
install package issue 

### ISSUE THREAD

**Issue by MrszhuL** [CommunityGD32Cores/ArduinoCore-GD32#83]
OS: macOS12.6.6
IDE: vscode with arduino-cli
```shell
[Starting] Install package - GD32Community...
GD32Community:gd32:0.0.1
Invalid argument passed: Found 0 platform for reference "GD32Community:gd32@0.0.1":

[Error] Exit with code=7
```
When I add the url to Arduino settings and want to install this package some problems occurred like above. 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/57440504/229523815-af9eadc3-7222-47f5-9e82-09e8432bb312.png">
I have googled it but nothing found, so how to aim the problem and shoot it down?

**Comment by maxgerhardt** [comment]
I have never used no registered anything with the Arduino-CLI ecosystem.

How can I reproduce what the error message? Some batch script / reproduction steps?

**Comment by MrszhuL** [comment]
1. Var homebrew to install Arduino-cli
```shell
brew install arduino-cli
```
2. In vscode Arduino settings add url in the red box (ps: I can promise that this json in this IP address is as same as yours, because I just copy it to my server due to the GFW😞 )
<img width="915" alt="image" src="https://user-images.githubusercontent.com/57440504/229527078-1b5987cf-129d-45de-8430-21fb6d6af69f.png">
3. then choose the board in board manager and click install. the problem maybe arise in output
<img width="626" alt="image" src="https://user-images.githubusercontent.com/57440504/229528593-cfa0643d-76d5-4400-86ec-fe698215fc34.png">

**Comment by maxgerhardt** [comment]
>In vscode Arduino settings 

Which extension is that exactly? Are we talking Arduino IDE 2.0 or this Microsoft extension

![grafik](https://user-images.githubusercontent.com/26485477/232207124-a2c7804c-61ba-4fff-89a5-bcdbec897487.png)

Since there is no "arduino-cli" extension

![grafik](https://user-images.githubusercontent.com/26485477/232207137-d16c03e8-94f8-41a3-9c3b-9dd2e7091f39.png)

**Comment by MrszhuL** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/57440504/232207539-14121c57-87c9-4cb7-8e70-7622dabc3736.png">
Yes, I have used this extension. Arduino-CLI is not an extension, it may be available from this [website](https://arduino.github.io/arduino-cli/0.19/installation/).

> Add URL in the red box

The above quote can be found in the picture below:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/57440504/232208411-36a86ae5-90a6-4743-8711-1a02cbc5800e.png">

**Comment by maxgerhardt** [comment]
While this is not fixed, can you use VSCode but deactivate the Arduino extension and install the "PlatformIO" extension and follow https://github.com/CommunityGD32Cores/gd32-pio-projects#general-usage-notes?

**Comment by MrszhuL** [comment]
Thank you for your warm heart, I will follow this guide. 👍🏻
