### ISSUE TITLE
GD32F350CB "Not declared" error on Arduino 1.8.13

### ISSUE THREAD

**Issue by ldicdican** [CommunityGD32Cores/ArduinoCore-GD32#86]
https://github.com/CommunityGD32Cores/ArduinoCore-GD32/blob/c2bfff7740ec2dc58478a5eddaa537c49b7df885/variants/GD32F350CB_GENERIC/PeripheralNames.h#L42

(int)DAC0 -> (int)DAC

**Comment by maxgerhardt** [comment]
Thanks, we'll have to correct that in the generation script.

https://github.com/CommunityGD32Cores/platform-gd32/blob/main/misc/scripts/gd32_genpinmap/pinmap_converter.py

**Comment by maxgerhardt** [comment]
Fixed in https://github.com/CommunityGD32Cores/platform-gd32/commit/77f0bcd0e5328a9a28849392f1a471e858c70d77 and https://github.com/CommunityGD32Cores/ArduinoCore-GD32/commit/7b597ba8fb08af6e382e2e1a9617ed673b4afeee
