### ISSUE TITLE
Issue on GD32F350

### ISSUE THREAD

**Issue by ldicdican** [CommunityGD32Cores/ArduinoCore-GD32#87]
https://github.com/CommunityGD32Cores/ArduinoCore-GD32/blob/c2bfff7740ec2dc58478a5eddaa537c49b7df885/variants/GD32F350CB_GENERIC/PeripheralPins.c#L114

Should be commented this out::

GPIO_AF_9,             /* 8 */
 GPIO_AF_11

Plus the 2 entries below with 9 and 11 pins

DAC0 -> DAC

**Comment by maxgerhardt** [comment]
Fixed in https://github.com/CommunityGD32Cores/platform-gd32/commit/77f0bcd0e5328a9a28849392f1a471e858c70d77 and https://github.com/CommunityGD32Cores/ArduinoCore-GD32/commit/7b597ba8fb08af6e382e2e1a9617ed673b4afeee
